services:
  app:
    build: 
      context: .
      # args:
      #   - DATABASE_URL=postgres://dbuser:password@db:5432/avalibility
      # network: host
    depends_on:
      - db
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /usr/local/bin/
    environment:
      - DATABASE_URL=postgres://dbuser:password@db:5432/avalibility
  db:
    image: postgres:16.1-alpine
    volumes:
      - team-avail-data:/var/lib/postgresql/data
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  team-avail-data:
